services:
  backend:
    build: .
    image: emoguard-backend:local

  celery-worker:
    build: .
    image: emoguard-backend:local

  celery-beat:
    build: .
    image: emoguard-backend:local

  nginx:
    build:
      context: .
      dockerfile: nginx_build\Dockerfile
    image: emoguard-nginx:local
